# Generated by Django 4.2.1 on 2023-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('raca', models.CharField(max_length=70)),
                ('forca', models.FloatField()),
                ('destreza', models.FloatField()),
                ('construcao', models.FloatField()),
                ('inteligencia', models.FloatField()),
                ('sabedoria', models.FloatField()),
                ('classe_armadura', models.FloatField()),
                ('iniciativa', models.FloatField()),
                ('deslocamento', models.FloatField()),
                ('ponto_vida_max', models.FloatField()),
                ('pontos_vida_atual', models.FloatField()),
                ('pontos_vida_temp', models.FloatField()),
                ('equipamentos', models.TextField()),
                ('tracos_personalidade', models.TextField()),
                ('ideais', models.TextField()),
                ('vinculos', models.TextField()),
                ('fraquezas', models.TextField()),
            ],
        ),
    ]
