# Generated by Django 4.2.1 on 2023-06-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_characters_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='classe_armadura',
            new_name='armor_class',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='construcao',
            new_name='construction',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='deslocamento',
            new_name='current_life_points',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='destreza',
            new_name='dexterity',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='forca',
            new_name='displacement',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='equipamentos',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='fraquezas',
            new_name='ideals',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='iniciativa',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='inteligencia',
            new_name='intelligence',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ideais',
            new_name='links',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='ponto_vida_max',
            new_name='max_life_point',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='pontos_vida_atual',
            new_name='points_life_temp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='raca',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='pontos_vida_temp',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tracos_personalidade',
            new_name='traits_personality',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='vinculos',
            new_name='weaknesses',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='sabedoria',
            new_name='wisdom',
        ),
    ]
